//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoundingVolume.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Cloud\\SkyDrive\\Documents\\UNIFEI\\TCC\\Dataset\\glass\\glass.data")]
        public string dataset_path {
            get {
                return ((string)(this["dataset_path"]));
            }
            set {
                this["dataset_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Cloud\\SkyDrive\\Documents\\UNIFEI\\TCC\\Dataset\\NSL_KDD\\")]
        public string ids_dataset_dir {
            get {
                return ((string)(this["ids_dataset_dir"]));
            }
            set {
                this["ids_dataset_dir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("training.txt")]
        public string ids_train_file {
            get {
                return ((string)(this["ids_train_file"]));
            }
            set {
                this["ids_train_file"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("part")]
        public string ids_test_dir {
            get {
                return ((string)(this["ids_test_dir"]));
            }
            set {
                this["ids_test_dir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("training_attack_types.txt")]
        public string ids_cat_file {
            get {
                return ((string)(this["ids_cat_file"]));
            }
            set {
                this["ids_cat_file"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int xFold {
            get {
                return ((int)(this["xFold"]));
            }
            set {
                this["xFold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kddcup.data.corrected")]
        public string ids_dataset_full {
            get {
                return ((string)(this["ids_dataset_full"]));
            }
            set {
                this["ids_dataset_full"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ids_mode {
            get {
                return ((bool)(this["ids_mode"]));
            }
            set {
                this["ids_mode"] = value;
            }
        }
    }
}
